package com.itextpdf.text.pdf;

import androidx.exifinterface.media.ExifInterface;
import com.google.common.net.HttpHeaders;
import com.itextpdf.text.error_messages.MessageLocalization;
import com.itextpdf.text.xml.xmp.PdfProperties;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;

public class PdfName extends PdfObject implements Comparable<PdfName> {
    public static final PdfName A3 = new PdfName("Adobe.PPKMS");
    public static final PdfName A4 = new PdfName("BleedBox");
    public static final PdfName A5 = new PdfName("CollectionItem");
    public static final PdfName A6 = new PdfName("DeviceGray");
    public static final PdfName A7 = new PdfName("ExtensionLevel");
    public static final PdfName A8 = new PdfName("FRM");
    public static final PdfName A9 = new PdfName("ID");
    public static final PdfName Aa = new PdfName("Linear");
    public static final PdfName Ab = new PdfName("Next");
    public static final PdfName Ac = new PdfName("PaintType");
    public static final PdfName Ad = new PdfName("Q");
    public static final PdfName Ae = new PdfName("RunLengthDecode");
    public static final PdfName Af = new PdfName("Subject");
    public static final PdfName Ag = new PdfName("TrueType");
    public static final PdfName Ah = new PdfName("VOffset");
    public static final PdfName B3 = new PdfName("AESV2");
    public static final PdfName B4 = new PdfName("Blinds");
    public static final PdfName B5 = new PdfName("CollectionSchema");
    public static final PdfName B6 = new PdfName("DeviceRGB");
    public static final PdfName B7 = new PdfName("ExtGState");
    public static final PdfName B8 = new PdfName("FS");
    public static final PdfName B9 = new PdfName("Identity");
    public static final PdfName Ba = new PdfName("LineHeight");
    public static final PdfName Bb = new PdfName("NextPage");
    public static final PdfName Bc = new PdfName("Panose");
    public static final PdfName Bd = new PdfName("QuadPoints");
    public static final PdfName Be = new PdfName("RV");
    public static final PdfName Bf = new PdfName("SubmitForm");
    public static final PdfName Bg = new PdfName("TS");
    public static final PdfName Bh = new PdfName("VP");
    public static final PdfName C3 = new PdfName("AESV3");
    public static final PdfName C4 = new PdfName("BM");
    public static final PdfName C5 = new PdfName("CollectionSort");
    public static final PdfName C6 = new PdfName("DeviceCMYK");
    public static final PdfName C7 = new PdfName("Export");
    public static final PdfName C8 = new PdfName("FT");
    public static final PdfName C9 = new PdfName("IDTree");
    public static final PdfName Ca = new PdfName(HttpHeaders.s0);
    public static final PdfName Cb = new PdfName("NM");
    public static final PdfName Cc = new PdfName("Params");
    public static final PdfName Cd = new PdfName("Quote");
    public static final PdfName Ce = new PdfName(ExifInterface.R4);
    public static final PdfName Cf = new PdfName("Subtype");
    public static final PdfName Cg = new PdfName("Ttl");
    public static final PdfName Ch = new PdfName("VRI");
    public static final PdfName D3 = new PdfName("AF");
    public static final PdfName D4 = new PdfName("Border");
    public static final PdfName D5 = new PdfName("CollectionSubitem");
    public static final PdfName D6 = new PdfName("DeviceN");
    public static final PdfName D7 = new PdfName("ExportState");
    public static final PdfName D8 = new PdfName("FullScreen");
    public static final PdfName D9 = new PdfName("IF");
    public static final PdfName Da = new PdfName("List");
    public static final PdfName Db = new PdfName("None");
    public static final PdfName Dc = new PdfName("Parent");
    public static final PdfName Dd = new PdfName("R");
    public static final PdfName De = new PdfName(ExifInterface.l1);
    public static final PdfName Df = new PdfName("Summary");
    public static final PdfName Dg = new PdfName("TU");
    public static final PdfName Dh = new PdfName(ExifInterface.T4);
    public static final PdfName E3 = new PdfName("AFRelationship");
    public static final PdfName E4 = new PdfName("Both");
    public static final PdfName E5 = new PdfName("ColSpan");
    public static final PdfName E6 = new PdfName("Di");
    public static final PdfName E7 = new PdfName("Event");
    public static final PdfName E8 = new PdfName("Function");
    public static final PdfName E9 = new PdfName("IM");
    public static final PdfName Ea = new PdfName("ListMode");
    public static final PdfName Eb = new PdfName("NonFullScreenPageMode");
    public static final PdfName Ec = new PdfName("ParentTree");
    public static final PdfName Ed = new PdfName("R2L");
    public static final PdfName Ee = new PdfName("Schema");
    public static final PdfName Ef = new PdfName("Supplement");
    public static final PdfName Eg = new PdfName("tv");
    public static final PdfName Eh = new PdfName("W2");
    public static final PdfName F3 = new PdfName("AHx");
    public static final PdfName F4 = new PdfName("Bounds");
    public static final PdfName F5 = new PdfName("Column");
    public static final PdfName F6 = new PdfName("Differences");
    public static final PdfName F7 = new PdfName("F");
    public static final PdfName F8 = new PdfName("Functions");
    public static final PdfName F9 = new PdfName("Image");
    public static final PdfName Fa = new PdfName("ListNumbering");
    public static final PdfName Fb = new PdfName("NonStruct");
    public static final PdfName Fc = new PdfName("ParentTreeNextKey");
    public static final PdfName Fd = new PdfName(HttpHeaders.I);
    public static final PdfName Fe = new PdfName("Scope");
    public static final PdfName Ff = new PdfName("SV");
    public static final PdfName Fg = new PdfName("TwoColumnLeft");
    public static final PdfName Fh = new PdfName("Warichu");
    public static final PdfName G3 = new PdfName("AIS");
    public static final PdfName G4 = new PdfName("Box");
    public static final PdfName G5 = new PdfName("Columns");
    public static final PdfName G6 = new PdfName("Dissolve");
    public static final PdfName G7 = new PdfName("Far");
    public static final PdfName G8 = new PdfName("FunctionType");
    public static final PdfName G9 = new PdfName("ImageB");
    public static final PdfName Ga = new PdfName(HttpHeaders.t0);
    public static final PdfName Gb = new PdfName("Not");
    public static final PdfName Gc = new PdfName("Part");
    public static final PdfName Gd = new PdfName("RB");
    public static final PdfName Ge = new PdfName("Screen");
    public static final PdfName Gf = new PdfName("SW");
    public static final PdfName Gg = new PdfName("TwoColumnRight");
    public static final PdfName Gh = new PdfName("Watermark");
    public static final PdfName H3 = new PdfName("All");
    public static final PdfName H4 = new PdfName("BS");
    public static final PdfName H5 = new PdfName("Condition");
    public static final PdfName H6 = new PdfName("Direction");
    public static final PdfName H7 = new PdfName("FB");
    public static final PdfName H8 = new PdfName(ExifInterface.e0);
    public static final PdfName H9 = new PdfName("ImageC");
    public static final PdfName Ha = new PdfName("Lock");
    public static final PdfName Hb = new PdfName("Note");
    public static final PdfName Hc = new PdfName("PassContextClick");
    public static final PdfName Hd = new PdfName("rb");
    public static final PdfName He = new PdfName("Scripts");
    public static final PdfName Hf = new PdfName("Symbol");
    public static final PdfName Hg = new PdfName("TwoPageLeft");
    public static final PdfName Hh = new PdfName("WC");
    public static final PdfName I3 = new PdfName("AllPages");
    public static final PdfName I4 = new PdfName("Btn");
    public static final PdfName I5 = new PdfName("Configs");
    public static final PdfName I6 = new PdfName("DisplayDocTitle");
    public static final PdfName I7 = new PdfName("FD");
    public static final PdfName I8 = new PdfName("GBK");
    public static final PdfName I9 = new PdfName("ImageI");
    public static final PdfName Ia = new PdfName("Locked");
    public static final PdfName Ib = new PdfName("NumberFormat");
    public static final PdfName Ic = new PdfName("Pattern");
    public static final PdfName Id = new PdfName("RBGroups");
    public static final PdfName Ie = new PdfName("Sect");
    public static final PdfName If = new PdfName(ExifInterface.d5);
    public static final PdfName Ig = new PdfName("TwoPageRight");
    public static final PdfName Ih = new PdfName("Widget");
    public static final PdfName J3 = new PdfName("Alt");
    public static final PdfName J4 = new PdfName("ByteRange");
    public static final PdfName J5 = new PdfName("Configuration");
    public static final PdfName J6 = new PdfName("Div");
    public static final PdfName J7 = new PdfName("FDecodeParms");
    public static final PdfName J8 = new PdfName("GCS");
    public static final PdfName J9 = new PdfName("ImageMask");
    public static final PdfName Ja = new PdfName("LowerAlpha");
    public static final PdfName Jb = new PdfName("NumCopies");
    public static final PdfName Jc = new PdfName("PatternType");
    public static final PdfName Jd = new PdfName("RC");
    public static final PdfName Je = new PdfName("Separation");
    public static final PdfName Jf = new PdfName("TA");
    public static final PdfName Jg = new PdfName("Tx");
    public static final PdfName Jh = new PdfName(HttpHeaders.v1);
    public static final PdfName K3 = new PdfName("Alternate");
    public static final PdfName K4 = new PdfName("C");
    public static final PdfName K5 = new PdfName("Configurations");
    public static final PdfName K6 = new PdfName("DL");
    public static final PdfName K7 = new PdfName("FDF");
    public static final PdfName K8 = new PdfName("GEO");
    public static final PdfName K9 = new PdfName("Include");
    public static final PdfName Ka = new PdfName("LowerRoman");
    public static final PdfName Kb = new PdfName("Nums");
    public static final PdfName Kc = new PdfName("pb");
    public static final PdfName Kd = new PdfName("RD");
    public static final PdfName Ke = new PdfName("SetOCGState");
    public static final PdfName Kf = new PdfName("Table");
    public static final PdfName Kg = new PdfName("Type");
    public static final PdfName Kh = new PdfName("Widths");
    public static final PdfName L3 = new PdfName("AlternatePresentations");
    public static final PdfName L4 = new PdfName("C0");
    public static final PdfName L5 = new PdfName("ContactInfo");
    public static final PdfName L6 = new PdfName("Dm");
    public static final PdfName L7 = new PdfName("Ff");
    public static final PdfName L8 = new PdfName("GEOGCS");
    public static final PdfName L9 = new PdfName("Ind");
    public static final PdfName La = new PdfName("LPTS");
    public static final PdfName Lb = new PdfName("O");
    public static final PdfName Lc = new PdfName("PC");
    public static final PdfName Ld = new PdfName("Reason");
    public static final PdfName Le = new PdfName("Settings");
    public static final PdfName Lf = new PdfName("Tabs");
    public static final PdfName Lg = new PdfName("Type0");
    public static final PdfName Lh = new PdfName("Win");
    public static final PdfName M3 = new PdfName("Alternates");
    public static final PdfName M4 = new PdfName("C1");
    public static final PdfName M5 = new PdfName("Content");
    public static final PdfName M6 = new PdfName("DocMDP");
    public static final PdfName M7 = new PdfName("FFilter");
    public static final PdfName M8 = new PdfName("Glitter");
    public static final PdfName M9 = new PdfName("Index");
    public static final PdfName Ma = new PdfName("LZWDecode");
    public static final PdfName Mb = new PdfName("Obj");
    public static final PdfName Mc = new PdfName(PdfObject.g3);
    public static final PdfName Md = new PdfName("Recipients");
    public static final PdfName Me = new PdfName("Shading");
    public static final PdfName Mf = new PdfName("TBody");
    public static final PdfName Mg = new PdfName("Type1");
    public static final PdfName Mh = new PdfName("WinAnsiEncoding");
    public static final PdfName N3 = new PdfName("And");
    public static final PdfName N4 = new PdfName("CA");
    public static final PdfName N5 = new PdfName("Contents");
    public static final PdfName N6 = new PdfName("DocOpen");
    public static final PdfName N7 = new PdfName("FG");
    public static final PdfName N8 = new PdfName("GoTo");
    public static final PdfName N9 = new PdfName("Indexed");
    public static final PdfName Na = new PdfName("M");
    public static final PdfName Nb = new PdfName("OBJR");
    public static final PdfName Nc = new PdfName("PDFDocEncoding");
    public static final PdfName Nd = new PdfName("Rect");
    public static final PdfName Ne = new PdfName("ShadingType");
    public static final PdfName Nf = new PdfName("TD");
    public static final PdfName Ng = new PdfName("Type3");
    public static final PdfName Nh = new PdfName("Window");
    public static final PdfName O3 = new PdfName("Animation");
    public static final PdfName O4 = new PdfName("ca");
    public static final PdfName O5 = new PdfName("Coords");
    public static final PdfName O6 = new PdfName("DocTimeStamp");
    public static final PdfName O7 = new PdfName("FieldMDP");
    public static final PdfName O8 = new PdfName("GoTo3DView");
    public static final PdfName O9 = new PdfName("Info");
    public static final PdfName Oa = new PdfName("Mac");
    public static final PdfName Ob = new PdfName("ObjStm");
    public static final PdfName Oc = new PdfName("PDU");
    public static final PdfName Od = new PdfName("Redact");
    public static final PdfName Oe = new PdfName("Shift-JIS");
    public static final PdfName Of = new PdfName("TR");
    public static final PdfName Og = new PdfName("U");
    public static final PdfName Oh = new PdfName("Windowed");
    public static final PdfName P3 = new PdfName("Annot");
    public static final PdfName P4 = new PdfName("CalGray");
    public static final PdfName P5 = new PdfName("Count");
    public static final PdfName P6 = new PdfName("Document");
    public static final PdfName P7 = new PdfName("Fields");
    public static final PdfName P8 = new PdfName("GoToE");
    public static final PdfName P9 = new PdfName("Ink");
    public static final PdfName Pa = new PdfName("Material");
    public static final PdfName Pb = new PdfName("OC");
    public static final PdfName Pc = new PdfName("Perceptual");
    public static final PdfName Pd = new PdfName("Reference");
    public static final PdfName Pe = new PdfName("Sig");
    public static final PdfName Pf = new PdfName("TR2");
    public static final PdfName Pg = new PdfName("UE");
    public static final PdfName Ph = new PdfName("Wipe");
    public static final PdfName Q3 = new PdfName("Annots");
    public static final PdfName Q4 = new PdfName("CalRGB");
    public static final PdfName Q5 = new PdfName("Courier");
    public static final PdfName Q6 = new PdfName("Domain");
    public static final PdfName Q7 = new PdfName("Figure");
    public static final PdfName Q8 = new PdfName("GoToR");
    public static final PdfName Q9 = new PdfName("InkList");
    public static final PdfName Qa = new PdfName("Matrix");
    public static final PdfName Qb = new PdfName("OCG");
    public static final PdfName Qc = new PdfName("Perms");
    public static final PdfName Qd = new PdfName("Registry");
    public static final PdfName Qe = new PdfName("SigFieldLock");
    public static final PdfName Qf = new PdfName("Text");
    public static final PdfName Qg = new PdfName("UF");
    public static final PdfName Qh = new PdfName(ExifInterface.Q);
    public static final PdfName R3 = new PdfName("AntiAlias");
    public static final PdfName R4 = new PdfName("CapHeight");
    public static final PdfName R5 = new PdfName("Courier-Bold");
    public static final PdfName R6 = new PdfName("DOS");
    public static final PdfName R7 = new PdfName("FileAttachment");
    public static final PdfName R8 = new PdfName("GPTS");
    public static final PdfName R9 = new PdfName("Instances");
    public static final PdfName Ra = new PdfName("MacExpertEncoding");
    public static final PdfName Rb = new PdfName("OCGs");
    public static final PdfName Rc = new PdfName("Pg");
    public static final PdfName Rd = new PdfName("RegistryName");
    public static final PdfName Re = new PdfName("SigFlags");
    public static final PdfName Rf = new PdfName("TextAlign");
    public static final PdfName Rg = new PdfName("UHC");
    public static final PdfName Rh = new PdfName("WKT");
    public static final PdfName S3 = new PdfName("AP");
    public static final PdfName S4 = new PdfName("Caret");
    public static final PdfName S5 = new PdfName("Courier-Oblique");
    public static final PdfName S6 = new PdfName("DP");
    public static final PdfName S7 = new PdfName("Filespec");
    public static final PdfName S8 = new PdfName("Group");
    public static final PdfName S9 = new PdfName("ImportData");
    public static final PdfName Sa = new PdfName("MacRomanEncoding");
    public static final PdfName Sb = new PdfName("OCMD");
    public static final PdfName Sc = new PdfName("PI");
    public static final PdfName Sd = new PdfName("RelativeColorimetric");
    public static final PdfName Se = new PdfName("SigRef");
    public static final PdfName Sf = new PdfName("TextDecorationColor");
    public static final PdfName Sg = new PdfName("Underline");
    public static final PdfName Sh = new PdfName("WP");
    public static final PdfName T3 = new PdfName("App");
    public static final PdfName T4 = new PdfName("Caption");
    public static final PdfName T5 = new PdfName("Courier-BoldOblique");
    public static final PdfName T6 = new PdfName("DR");
    public static final PdfName T7 = new PdfName("Filter");
    public static final PdfName T8 = new PdfName("GTS_PDFA1");
    public static final PdfName T9 = new PdfName("Intent");
    public static final PdfName Ta = new PdfName("Marked");
    public static final PdfName Tb = new PdfName("OCProperties");
    public static final PdfName Tc = new PdfName("PickTrayByPDFSize");
    public static final PdfName Td = new PdfName("Rendition");
    public static final PdfName Te = new PdfName("Simplex");
    public static final PdfName Tf = new PdfName("TextDecorationThickness");
    public static final PdfName Tg = new PdfName("Unix");
    public static final PdfName Th = new PdfName("WS");
    public static final PdfName U3 = new PdfName("AppDefault");
    public static final PdfName U4 = new PdfName("Catalog");
    public static final PdfName U5 = new PdfName("CreationDate");
    public static final PdfName U6 = new PdfName("DS");
    public static final PdfName U7 = new PdfName("First");
    public static final PdfName U8 = new PdfName("GTS_PDFX");
    public static final PdfName U9 = new PdfName("Interpolate");
    public static final PdfName Ua = new PdfName("MarkInfo");
    public static final PdfName Ub = new PdfName("OCSP");
    public static final PdfName Uc = new PdfName("PieceInfo");
    public static final PdfName Ud = new PdfName("Repeat");
    public static final PdfName Ue = new PdfName("SinglePage");
    public static final PdfName Uf = new PdfName("TextDecorationType");
    public static final PdfName Ug = new PdfName("UpperAlpha");
    public static final PdfName Uh = new PdfName("WT");
    public static final PdfName V3 = new PdfName("Art");
    public static final PdfName V4 = new PdfName("Category");
    public static final PdfName V5 = new PdfName("Creator");
    public static final PdfName V6 = new PdfName("DSS");
    public static final PdfName V7 = new PdfName("FirstChar");
    public static final PdfName V8 = new PdfName("GTS_PDFXVersion");
    public static final PdfName V9 = new PdfName("IsMap");
    public static final PdfName Va = new PdfName("Mask");
    public static final PdfName Vb = new PdfName("OCSPs");
    public static final PdfName Vc = new PdfName("PlayCount");
    public static final PdfName Vd = new PdfName("ResetForm");
    public static final PdfName Ve = new PdfName("Size");
    public static final PdfName Vf = new PdfName("TextIndent");
    public static final PdfName Vg = new PdfName("UpperRoman");
    public static final PdfName Vh = new PdfName("X");
    public static final PdfName W3 = new PdfName("ArtBox");
    public static final PdfName W4 = new PdfName("cb");
    public static final PdfName W5 = new PdfName("CreatorInfo");
    public static final PdfName W6 = new PdfName("Dur");
    public static final PdfName W7 = new PdfName("FirstPage");
    public static final PdfName W8 = new PdfName("H");
    public static final PdfName W9 = new PdfName("IRT");
    public static final PdfName Wa = new PdfName("max");
    public static final PdfName Wb = new PdfName("OE");
    public static final PdfName Wc = new PdfName("PO");
    public static final PdfName Wd = new PdfName("Resources");
    public static final PdfName We = new PdfName("SMask");
    public static final PdfName Wf = new PdfName("TFoot");
    public static final PdfName Wg = new PdfName("UR");
    public static final PdfName Wh = new PdfName("XA");
    public static final PdfName X3 = new PdfName("Artifact");
    public static final PdfName X4 = new PdfName("CCITTFaxDecode");
    public static final PdfName X5 = new PdfName("CRL");
    public static final PdfName X6 = new PdfName("Duplex");
    public static final PdfName X7 = new PdfName("Fit");
    public static final PdfName X8 = new PdfName("H1");
    public static final PdfName X9 = new PdfName("ItalicAngle");
    public static final PdfName Xa = new PdfName("Max");
    public static final PdfName Xb = new PdfName("Off");
    public static final PdfName Xc = new PdfName("Polygon");
    public static final PdfName Xd = new PdfName("Requirements");
    public static final PdfName Xe = new PdfName("SMaskInData");
    public static final PdfName Xf = new PdfName("TH");
    public static final PdfName Xg = new PdfName("UR3");
    public static final PdfName Xh = new PdfName("XD");
    public static final PdfName Y3 = new PdfName("Ascent");
    public static final PdfName Y4 = new PdfName("Center");
    public static final PdfName Y5 = new PdfName("CRLs");
    public static final PdfName Y6 = new PdfName("DuplexFlipShortEdge");
    public static final PdfName Y7 = new PdfName("FitH");
    public static final PdfName Y8 = new PdfName("H2");
    public static final PdfName Y9 = new PdfName("ITXT");
    public static final PdfName Ya = new PdfName("MaxLen");
    public static final PdfName Yb = new PdfName("OFF");
    public static final PdfName Yc = new PdfName("PolyLine");
    public static final PdfName Yd = new PdfName("ReversedChars");
    public static final PdfName Ye = new PdfName("Sort");
    public static final PdfName Yf = new PdfName("THead");
    public static final PdfName Yg = new PdfName("URI");
    public static final PdfName Yh = new PdfName("XFA");
    public static final PdfName Z3 = new PdfName("AS");
    public static final PdfName Z4 = new PdfName("CenterWindow");
    public static final PdfName Z5 = new PdfName("CropBox");
    public static final PdfName Z6 = new PdfName("DuplexFlipLongEdge");
    public static final PdfName Z7 = new PdfName("FitV");
    public static final PdfName Z8 = new PdfName("H3");
    public static final PdfName Z9 = new PdfName("IX");
    public static final PdfName Za = new PdfName("MediaBox");
    public static final PdfName Zb = new PdfName("ON");
    public static final PdfName Zc = new PdfName("Popup");
    public static final PdfName Zd = new PdfName("RI");
    public static final PdfName Ze = new PdfName("Sound");
    public static final PdfName Zf = new PdfName("Thumb");
    public static final PdfName Zg = new PdfName("URL");
    public static final PdfName Zh = new PdfName("XML");
    public static final PdfName a4 = new PdfName("ASCII85Decode");
    public static final PdfName a5 = new PdfName("Cert");
    public static final PdfName a6 = new PdfName("Crypt");
    public static final PdfName a7 = new PdfName("DV");
    public static final PdfName a8 = new PdfName("FitR");
    public static final PdfName a9 = new PdfName("H4");
    public static final PdfName aa = new PdfName("JavaScript");
    public static final PdfName ab = new PdfName("MCID");
    public static final PdfName ac = new PdfName("OneColumn");
    public static final PdfName ad = new PdfName("Position");
    public static final PdfName ae = new PdfName("RichMedia");
    public static final PdfName af = new PdfName("SpaceAfter");
    public static final PdfName ag = new PdfName("Threads");
    public static final PdfName ah = new PdfName("Usage");
    public static final PdfName ai = new PdfName("XObject");
    public static final PdfName b4 = new PdfName("ASCIIHexDecode");
    public static final PdfName b5 = new PdfName("Certs");
    public static final PdfName b6 = new PdfName("CS");
    public static final PdfName b7 = new PdfName("DW");
    public static final PdfName b8 = new PdfName("FitB");
    public static final PdfName b9 = new PdfName("H5");
    public static final PdfName ba = new PdfName("JBIG2Decode");
    public static final PdfName bb = new PdfName("MCR");
    public static final PdfName bc = new PdfName("Open");
    public static final PdfName bd = new PdfName("Predictor");
    public static final PdfName be = new PdfName("RichMediaActivation");
    public static final PdfName bf = new PdfName("SpaceBefore");
    public static final PdfName bg = new PdfName("TI");
    public static final PdfName bh = new PdfName("UseAttachments");
    public static final PdfName bi = new PdfName("XPTS");
    public static final PdfName c4 = new PdfName("Asset");
    public static final PdfName c5 = new PdfName("CF");
    public static final PdfName c6 = new PdfName("CuePoint");
    public static final PdfName c7 = new PdfName(ExifInterface.S4);
    public static final PdfName c8 = new PdfName("FitBH");
    public static final PdfName c9 = new PdfName("H6");
    public static final PdfName ca = new PdfName("JBIG2Globals");
    public static final PdfName cb = new PdfName("Measure");
    public static final PdfName cc = new PdfName("OpenAction");
    public static final PdfName cd = new PdfName("Preferred");
    public static final PdfName ce = new PdfName("RichMediaAnimation");
    public static final PdfName cf = new PdfName("Span");
    public static final PdfName cg = new PdfName("Time");
    public static final PdfName ch = new PdfName("UseNone");
    public static final PdfName ci = new PdfName("XRef");
    public static final PdfName d4 = new PdfName("Assets");
    public static final PdfName d5 = new PdfName("CFM");
    public static final PdfName d6 = new PdfName("CuePoints");
    public static final PdfName d7 = new PdfName("EarlyChange");
    public static final PdfName d8 = new PdfName("FitBV");
    public static final PdfName d9 = new PdfName("HalftoneName");
    public static final PdfName da = new PdfName("JPXDecode");
    public static final PdfName db = new PdfName("Metadata");
    public static final PdfName dc = new PdfName("OP");
    public static final PdfName dd = new PdfName("Presentation");

    /* renamed from: de  reason: collision with root package name */
    public static final PdfName f26250de = new PdfName("RichMediaCommand");
    public static final PdfName df = new PdfName("Speed");
    public static final PdfName dg = new PdfName("TilingType");
    public static final PdfName dh = new PdfName("UseOC");
    public static final PdfName di = new PdfName("XRefStm");
    public static final PdfName e4 = new PdfName("Attached");
    public static final PdfName e5 = new PdfName("Ch");
    public static final PdfName e6 = new PdfName("CYX");
    public static final PdfName e7 = new PdfName("EF");
    public static final PdfName e8 = new PdfName("FitWindow");
    public static final PdfName e9 = new PdfName("HalftoneType");
    public static final PdfName ea = new PdfName("JS");
    public static final PdfName eb = new PdfName("min");
    public static final PdfName ec = new PdfName("op");
    public static final PdfName ed = new PdfName("PreserveRB");
    public static final PdfName ee = new PdfName("RichMediaConfiguration");
    public static final PdfName ef = new PdfName("Split");
    public static final PdfName eg = new PdfName("Times-Roman");
    public static final PdfName eh = new PdfName("UseOutlines");
    public static final PdfName ei = new PdfName("XStep");
    public static final PdfName f4 = new PdfName("AuthEvent");
    public static final PdfName f5 = new PdfName("CharProcs");
    public static final PdfName f6 = new PdfName("D");
    public static final PdfName f7 = new PdfName("EFF");
    public static final PdfName f8 = new PdfName("Fl");
    public static final PdfName f9 = new PdfName("HAlign");
    public static final PdfName fa = new PdfName("Justify");
    public static final PdfName fb = new PdfName("Min");
    public static final PdfName fc = new PdfName("OPI");
    public static final PdfName fd = new PdfName("PresSteps");
    public static final PdfName fe = new PdfName("RichMediaContent");
    public static final PdfName ff = new PdfName("Square");
    public static final PdfName fg = new PdfName("Times-Bold");
    public static final PdfName fh = new PdfName("User");

    /* renamed from: fi  reason: collision with root package name */
    public static final PdfName f26251fi = new PdfName("XYZ");
    public static final PdfName g4 = new PdfName("Author");
    public static final PdfName g5 = new PdfName("CheckSum");
    public static final PdfName g6 = new PdfName("DA");
    public static final PdfName g7 = new PdfName("EFOpen");
    public static final PdfName g8 = new PdfName("Flags");
    public static final PdfName g9 = new PdfName("Headers");
    public static final PdfName ga = new PdfName("K");
    public static final PdfName gb = new PdfName("MK");
    public static final PdfName gc = new PdfName("OPM");
    public static final PdfName gd = new PdfName("Prev");
    public static final PdfName ge = new PdfName("RichMediaDeactivation");
    public static final PdfName gf = new PdfName("Squiggly");
    public static final PdfName gg = new PdfName("Times-Italic");
    public static final PdfName gh = new PdfName("UserProperties");
    public static final PdfName gi = new PdfName("YStep");
    public static final PdfName h4 = new PdfName("B");
    public static final PdfName h5 = new PdfName("CI");
    public static final PdfName h6 = new PdfName("Data");
    public static final PdfName h7 = new PdfName("Embedded");
    public static final PdfName h8 = new PdfName(ExifInterface.P0);
    public static final PdfName h9 = new PdfName("Height");
    public static final PdfName ha = new PdfName(PdfProperties.f27409a);
    public static final PdfName hb = new PdfName("MMType1");
    public static final PdfName hc = new PdfName("Opt");
    public static final PdfName hd = new PdfName("PrevPage");
    public static final PdfName he = new PdfName("RichMediaExecute");
    public static final PdfName hf = new PdfName("SS");
    public static final PdfName hg = new PdfName("Times-BoldItalic");
    public static final PdfName hh = new PdfName("UserUnit");
    public static final PdfName hi = new PdfName("ZaDb");
    public static final PdfName i4 = new PdfName("Background");
    public static final PdfName i5 = new PdfName("CIDFontType0");
    public static final PdfName i6 = new PdfName("DC");
    public static final PdfName i7 = new PdfName("EmbeddedFile");
    public static final PdfName i8 = new PdfName("FlashVars");
    public static final PdfName i9 = new PdfName("Helv");
    public static final PdfName ia = new PdfName("Kids");
    public static final PdfName ib = new PdfName("ModDate");
    public static final PdfName ic = new PdfName("Or");
    public static final PdfName id = new PdfName("Print");
    public static final PdfName ie = new PdfName("RichMediaInstance");

    /* renamed from: if  reason: not valid java name */
    public static final PdfName f6if = new PdfName("St");
    public static final PdfName ig = new PdfName("Title");
    public static final PdfName ih = new PdfName("UseThumbs");
    public static final PdfName ii = new PdfName("ZapfDingbats");
    public static final PdfName j3 = new PdfName("3D");
    public static final PdfName j4 = new PdfName("BackgroundColor");
    public static final PdfName j5 = new PdfName("CIDFontType2");
    public static final PdfName j6 = new PdfName("DCS");
    public static final PdfName j7 = new PdfName("EmbeddedFiles");
    public static final PdfName j8 = new PdfName("FlateDecode");
    public static final PdfName j9 = new PdfName("Helvetica");
    public static final PdfName ja = new PdfName("L");
    public static final PdfName jb = new PdfName("Movie");
    public static final PdfName jc = new PdfName("Order");
    public static final PdfName jd = new PdfName("PrintArea");
    public static final PdfName je = new PdfName("RichMediaParams");
    public static final PdfName jf = new PdfName("Stamp");
    public static final PdfName jg = new PdfName("TK");
    public static final PdfName jh = new PdfName("utf_8");
    public static final PdfName ji = new PdfName("Zoom");
    public static final PdfName k3 = new PdfName(ExifInterface.W4);
    public static final PdfName k4 = new PdfName("BaseEncoding");
    public static final PdfName k5 = new PdfName("CIDSet");
    public static final PdfName k6 = new PdfName("DCTDecode");
    public static final PdfName k7 = new PdfName("Encode");
    public static final PdfName k8 = new PdfName("Fo");
    public static final PdfName k9 = new PdfName("Helvetica-Bold");
    public static final PdfName ka = new PdfName("L2R");
    public static final PdfName kb = new PdfName("N");
    public static final PdfName kc = new PdfName("Ordering");
    public static final PdfName kd = new PdfName("PrintClip");
    public static final PdfName ke = new PdfName("RichMediaPosition");
    public static final PdfName kf = new PdfName("Status");
    public static final PdfName kg = new PdfName("TM");
    public static final PdfName kh = new PdfName(ExifInterface.X4);
    public static Map<String, PdfName> ki;
    public static final PdfName l3 = new PdfName("A85");
    public static final PdfName l4 = new PdfName("BaseFont");
    public static final PdfName l5 = new PdfName("CIDSystemInfo");
    public static final PdfName l6 = new PdfName("Decimal");
    public static final PdfName l7 = new PdfName("EncodedByteAlign");
    public static final PdfName l8 = new PdfName("Font");
    public static final PdfName l9 = new PdfName("Helvetica-Oblique");
    public static final PdfName la = new PdfName("Lab");
    public static final PdfName lb = new PdfName("n0");
    public static final PdfName lc = new PdfName("Org");
    public static final PdfName ld = new PdfName("PrinterMark");
    public static final PdfName le = new PdfName("RichMediaPresentation");
    public static final PdfName lf = new PdfName("Standard");
    public static final PdfName lg = new PdfName("TOC");
    public static final PdfName lh = new PdfName("V2");
    public static final PdfName m3 = new PdfName("AA");
    public static final PdfName m4 = new PdfName("BaseVersion");
    public static final PdfName m5 = new PdfName("CIDToGIDMap");
    public static final PdfName m6 = new PdfName("Deactivation");
    public static final PdfName m7 = new PdfName("Encoding");
    public static final PdfName m8 = new PdfName("FontBBox");
    public static final PdfName m9 = new PdfName("Helvetica-BoldOblique");
    public static final PdfName ma = new PdfName("Lang");
    public static final PdfName mb = new PdfName("n1");
    public static final PdfName mc = new PdfName("Oscillating");
    public static final PdfName md = new PdfName("PrintField");
    public static final PdfName me = new PdfName("RichMediaSettings");
    public static final PdfName mf = new PdfName("Start");
    public static final PdfName mg = new PdfName("TOCI");
    public static final PdfName mh = new PdfName("VAlign");
    public static final PdfName n3 = new PdfName("AbsoluteColorimetric");
    public static final PdfName n4 = new PdfName("BBox");
    public static final PdfName n5 = new PdfName("Circle");
    public static final PdfName n6 = new PdfName("Decode");
    public static final PdfName n7 = new PdfName("Encrypt");
    public static final PdfName n8 = new PdfName("FontDescriptor");
    public static final PdfName n9 = new PdfName("HF");
    public static final PdfName na = new PdfName("Language");
    public static final PdfName nb = new PdfName("n2");
    public static final PdfName nc = new PdfName("Outlines");
    public static final PdfName nd = new PdfName("PrintPageRange");
    public static final PdfName ne = new PdfName("RichMediaWindow");
    public static final PdfName nf = new PdfName("StartIndent");
    public static final PdfName ng = new PdfName("Toggle");
    public static final PdfName nh = new PdfName("VE");
    public static final PdfName o3 = new PdfName("AC");
    public static final PdfName o4 = new PdfName("BC");
    public static final PdfName o5 = new PdfName("ClassMap");
    public static final PdfName o6 = new PdfName("DecodeParms");
    public static final PdfName o7 = new PdfName("EncryptMetadata");
    public static final PdfName o8 = new PdfName("FontFamily");
    public static final PdfName o9 = new PdfName("Hid");
    public static final PdfName oa = new PdfName("Last");
    public static final PdfName ob = new PdfName("n3");
    public static final PdfName oc = new PdfName("OutputCondition");
    public static final PdfName od = new PdfName("PrintScaling");
    public static final PdfName oe = new PdfName("RL");
    public static final PdfName of = new PdfName("State");
    public static final PdfName og = new PdfName("Toolbar");
    public static final PdfName oh = new PdfName("VeriSign.PPKVS");
    public static final PdfName p3 = new PdfName("AcroForm");
    public static final PdfName p4 = new PdfName("BG");
    public static final PdfName p5 = new PdfName("Cloud");
    public static final PdfName p6 = new PdfName("Default");
    public static final PdfName p7 = new PdfName("End");
    public static final PdfName p8 = new PdfName("FontFile");
    public static final PdfName p9 = new PdfName("Hide");
    public static final PdfName pa = new PdfName("LastChar");
    public static final PdfName pb = new PdfName("n4");
    public static final PdfName pc = new PdfName("OutputConditionIdentifier");
    public static final PdfName pd = new PdfName("PrintState");
    public static final PdfName pe = new PdfName("Role");
    public static final PdfName pf = new PdfName("StdCF");
    public static final PdfName pg = new PdfName("ToUnicode");
    public static final PdfName ph = new PdfName("Version");
    public static final PdfName q3 = new PdfName("Action");
    public static final PdfName q4 = new PdfName("BibEntry");
    public static final PdfName q5 = new PdfName("CMD");
    public static final PdfName q6 = new PdfName("DefaultCryptFilter");
    public static final PdfName q7 = new PdfName("EndIndent");
    public static final PdfName q8 = new PdfName("FontFile2");
    public static final PdfName q9 = new PdfName("HideMenubar");
    public static final PdfName qa = new PdfName("LastPage");
    public static final PdfName qb = new PdfName("Name");
    public static final PdfName qc = new PdfName("OutputIntent");
    public static final PdfName qd = new PdfName("Private");
    public static final PdfName qe = new PdfName("RO");
    public static final PdfName qf = new PdfName("StemV");
    public static final PdfName qg = new PdfName("TP");
    public static final PdfName qh = new PdfName("Vertices");
    public static final PdfName r3 = new PdfName("Activation");
    public static final PdfName r4 = new PdfName("BigFive");
    public static final PdfName r5 = new PdfName("CO");
    public static final PdfName r6 = new PdfName("DefaultCMYK");
    public static final PdfName r7 = new PdfName("EndOfBlock");
    public static final PdfName r8 = new PdfName("FontFile3");
    public static final PdfName r9 = new PdfName("HideToolbar");
    public static final PdfName ra = new PdfName("Launch");
    public static final PdfName rb = new PdfName("Named");
    public static final PdfName rc = new PdfName("OutputIntents");
    public static final PdfName rd = new PdfName("ProcSet");
    public static final PdfName re = new PdfName("RoleMap");
    public static final PdfName rf = new PdfName("StmF");
    public static final PdfName rg = new PdfName("TR");
    public static final PdfName rh = new PdfName("Video");
    public static final PdfName s3 = new PdfName("ADBE");
    public static final PdfName s4 = new PdfName("Binding");
    public static final PdfName s5 = new PdfName("Code");
    public static final PdfName s6 = new PdfName("DefaultGray");
    public static final PdfName s7 = new PdfName("EndOfLine");
    public static final PdfName s8 = new PdfName("FontMatrix");
    public static final PdfName s9 = new PdfName("HideWindowUI");
    public static final PdfName sa = new PdfName("Layout");
    public static final PdfName sb = new PdfName("Names");
    public static final PdfName sc = new PdfName("OverlayText");
    public static final PdfName sd = new PdfName(PdfProperties.f27411c);
    public static final PdfName se = new PdfName("Root");
    public static final PdfName sf = new PdfName("StrF");
    public static final PdfName sg = new PdfName("Trans");
    public static final PdfName sh = new PdfName("View");
    public static final PdfName t3 = new PdfName("ActualText");
    public static final PdfName t4 = new PdfName("BindingMaterialName");
    public static final PdfName t5 = new PdfName("Color");
    public static final PdfName t6 = new PdfName("DefaultRGB");
    public static final PdfName t7 = new PdfName("EPSG");
    public static final PdfName t8 = new PdfName("FontName");
    public static final PdfName t9 = new PdfName("Highlight");
    public static final PdfName ta = new PdfName("Lbl");
    public static final PdfName tb = new PdfName("Navigation");
    public static final PdfName tc = new PdfName("P");
    public static final PdfName td = new PdfName("PROJCS");
    public static final PdfName te = new PdfName("Rotate");
    public static final PdfName tf = new PdfName("StrikeOut");
    public static final PdfName tg = new PdfName("TransformParams");
    public static final PdfName th = new PdfName("Views");
    public static final PdfName u3 = new PdfName("adbe.pkcs7.detached");
    public static final PdfName u4 = new PdfName("BitsPerComponent");
    public static final PdfName u5 = new PdfName("Colorants");
    public static final PdfName u6 = new PdfName("Desc");
    public static final PdfName u7 = new PdfName("ESIC");
    public static final PdfName u8 = new PdfName("FontWeight");
    public static final PdfName u9 = new PdfName("HOffset");
    public static final PdfName ua = new PdfName("LBody");
    public static final PdfName ub = new PdfName("NavigationPane");
    public static final PdfName uc = new PdfName("Page");
    public static final PdfName ud = new PdfName("Prop_Build");
    public static final PdfName ue = new PdfName("Row");
    public static final PdfName uf = new PdfName("StructElem");
    public static final PdfName ug = new PdfName("TransformMethod");
    public static final PdfName uh = new PdfName("ViewArea");
    public static final PdfName v3 = new PdfName("adbe.pkcs7.s4");
    public static final PdfName v4 = new PdfName(ExifInterface.z);
    public static final PdfName v5 = new PdfName("Colors");
    public static final PdfName v6 = new PdfName("DescendantFonts");
    public static final PdfName v7 = new PdfName("ETSI.CAdES.detached");
    public static final PdfName v8 = new PdfName("Foreground");
    public static final PdfName v9 = new PdfName("HT");
    public static final PdfName va = new PdfName("Length");
    public static final PdfName vb = new PdfName("NChannel");
    public static final PdfName vc = new PdfName("PageElement");
    public static final PdfName vd = new PdfName("Properties");
    public static final PdfName ve = new PdfName("Rows");
    public static final PdfName vf = new PdfName("StructParent");
    public static final PdfName vg = new PdfName("Transparency");
    public static final PdfName vh = new PdfName("ViewClip");
    public static final PdfName w3 = new PdfName("adbe.pkcs7.s5");
    public static final PdfName w4 = new PdfName("Bl");
    public static final PdfName w5 = new PdfName(ExifInterface.d0);
    public static final PdfName w6 = new PdfName("Descent");
    public static final PdfName w7 = new PdfName("ETSI.RFC3161");
    public static final PdfName w8 = new PdfName("Form");
    public static final PdfName w9 = new PdfName("HTP");
    public static final PdfName wa = new PdfName("Length1");
    public static final PdfName wb = new PdfName("Near");
    public static final PdfName wc = new PdfName("PageLabels");
    public static final PdfName wd = new PdfName("PS");
    public static final PdfName we = new PdfName("RowSpan");
    public static final PdfName wf = new PdfName("StructParents");
    public static final PdfName wg = new PdfName("Transparent");
    public static final PdfName wh = new PdfName("ViewerPreferences");
    public static final PdfName x3 = new PdfName("adbe.pkcs7.sha1");
    public static final PdfName x4 = new PdfName("BlackIs1");
    public static final PdfName x5 = new PdfName("ColorTransform");
    public static final PdfName x6 = new PdfName("Dest");
    public static final PdfName x7 = new PdfName("Exclude");
    public static final PdfName x8 = new PdfName("FormType");
    public static final PdfName x9 = new PdfName("I");
    public static final PdfName xa = new PdfName("LI");
    public static final PdfName xb = new PdfName("NeedAppearances");
    public static final PdfName xc = new PdfName("PageLayout");
    public static final PdfName xd = new PdfName("PtData");
    public static final PdfName xe = new PdfName("RP");
    public static final PdfName xf = new PdfName("StructTreeRoot");
    public static final PdfName xg = new PdfName("TrapNet");
    public static final PdfName xh = new PdfName("Viewport");
    public static final PdfName y3 = new PdfName("adbe.x509.rsa_sha1");
    public static final PdfName y4 = new PdfName("BlackPoint");
    public static final PdfName y5 = new PdfName("Collection");
    public static final PdfName y6 = new PdfName("DestOutputProfile");
    public static final PdfName y7 = new PdfName("Extend");
    public static final PdfName y8 = new PdfName("Formula");
    public static final PdfName y9 = new PdfName("IC");
    public static final PdfName ya = new PdfName("Limits");
    public static final PdfName yb = new PdfName("NeedsRendering");
    public static final PdfName yc = new PdfName("PageMode");
    public static final PdfName yd = new PdfName("Adobe.PubSec");
    public static final PdfName ye = new PdfName("RT");
    public static final PdfName yf = new PdfName("Style");
    public static final PdfName yg = new PdfName("Trapped");
    public static final PdfName yh = new PdfName("ViewState");
    public static final PdfName z3 = new PdfName("Adobe.PPKLite");
    public static final PdfName z4 = new PdfName("BlockQuote");
    public static final PdfName z5 = new PdfName("CollectionField");
    public static final PdfName z6 = new PdfName("Dests");
    public static final PdfName z7 = new PdfName("Extensions");
    public static final PdfName z8 = new PdfName("FreeText");
    public static final PdfName z9 = new PdfName("ICCBased");
    public static final PdfName za = new PdfName("Line");
    public static final PdfName zb = new PdfName("NewWindow");
    public static final PdfName zc = new PdfName("Pages");
    public static final PdfName zd = new PdfName("PV");
    public static final PdfName ze = new PdfName("Ruby");
    public static final PdfName zf = new PdfName("SubFilter");
    public static final PdfName zg = new PdfName("TrimBox");
    public static final PdfName zh = new PdfName("VisiblePages");
    private int i3;

    static {
        Class<PdfName> cls = PdfName.class;
        Field[] declaredFields = cls.getDeclaredFields();
        ki = new HashMap(declaredFields.length);
        int i2 = 0;
        while (i2 < declaredFields.length) {
            try {
                Field field = declaredFields[i2];
                if ((field.getModifiers() & 25) == 25 && field.getType().equals(cls)) {
                    PdfName pdfName = (PdfName) field.get((Object) null);
                    ki.put(a0(pdfName.toString()), pdfName);
                }
                i2++;
            } catch (Exception e2) {
                e2.printStackTrace();
                return;
            }
        }
    }

    public PdfName(String str) {
        this(str, true);
    }

    public static String a0(String str) {
        StringBuffer stringBuffer = new StringBuffer();
        try {
            int length = str.length();
            int i2 = 1;
            while (i2 < length) {
                char charAt = str.charAt(i2);
                if (charAt == '#') {
                    char charAt2 = str.charAt(i2 + 1);
                    i2 += 2;
                    charAt = (char) ((PRTokeniser.j(charAt2) << 4) + PRTokeniser.j(str.charAt(i2)));
                }
                stringBuffer.append(charAt);
                i2++;
            }
        } catch (IndexOutOfBoundsException unused) {
        }
        return stringBuffer.toString();
    }

    public static byte[] d0(String str) {
        int length = str.length();
        ByteBuffer byteBuffer = new ByteBuffer(length + 20);
        byteBuffer.c('/');
        char[] charArray = str.toCharArray();
        for (int i2 = 0; i2 < length; i2++) {
            char c2 = (char) (charArray[i2] & 255);
            if (c2 == ' ' || c2 == '#' || c2 == '%' || c2 == '/' || c2 == '<' || c2 == '>' || c2 == '[' || c2 == ']' || c2 == '{' || c2 == '}' || c2 == '(' || c2 == ')') {
                byteBuffer.c('#');
            } else if (c2 < ' ' || c2 > '~') {
                byteBuffer.c('#');
                if (c2 < 16) {
                    byteBuffer.c('0');
                }
            } else {
                byteBuffer.c(c2);
            }
            byteBuffer.k(Integer.toString(c2, 16));
        }
        return byteBuffer.F();
    }

    /* renamed from: Z */
    public int compareTo(PdfName pdfName) {
        byte[] bArr = this.s;
        byte[] bArr2 = pdfName.s;
        int min = Math.min(bArr.length, bArr2.length);
        for (int i2 = 0; i2 < min; i2++) {
            byte b2 = bArr[i2];
            byte b3 = bArr2[i2];
            if (b2 > b3) {
                return 1;
            }
            if (b2 < b3) {
                return -1;
            }
        }
        if (bArr.length < bArr2.length) {
            return -1;
        }
        return bArr.length > bArr2.length ? 1 : 0;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        return (obj instanceof PdfName) && compareTo((PdfName) obj) == 0;
    }

    public int hashCode() {
        int i2 = this.i3;
        if (i2 == 0) {
            int length = this.s.length;
            int i10 = 0;
            int i11 = 0;
            while (i10 < length) {
                i2 = (i2 * 31) + (this.s[i11] & 255);
                i10++;
                i11++;
            }
            this.i3 = i2;
        }
        return i2;
    }

    public PdfName(String str, boolean z) {
        super(4);
        this.i3 = 0;
        int length = str.length();
        if (!z || length <= 127) {
            this.s = d0(str);
            return;
        }
        throw new IllegalArgumentException(MessageLocalization.b("the.name.1.is.too.long.2.characters", str, String.valueOf(length)));
    }

    public PdfName(byte[] bArr) {
        super(4, bArr);
        this.i3 = 0;
    }
}
