package org.apache.commons.httpclient;

public class Header extends NameValuePair {
    private boolean isAutogenerated;

    public Header() {
        this((String) null, (String) null);
    }

    public HeaderElement[] getElements() {
        return HeaderElement.parseElements(getValue());
    }

    public HeaderElement[] getValues() throws HttpException {
        return HeaderElement.parse(getValue());
    }

    public boolean isAutogenerated() {
        return this.isAutogenerated;
    }

    public String toExternalForm() {
        StringBuffer stringBuffer = new StringBuffer();
        String str = "";
        stringBuffer.append(getName() == null ? str : getName());
        stringBuffer.append(": ");
        if (getValue() != null) {
            str = getValue();
        }
        stringBuffer.append(str);
        stringBuffer.append("\r\n");
        return stringBuffer.toString();
    }

    public String toString() {
        return toExternalForm();
    }

    public Header(String str, String str2) {
        super(str, str2);
        this.isAutogenerated = false;
    }

    public Header(String str, String str2, boolean z) {
        super(str, str2);
        this.isAutogenerated = z;
    }
}
